### ISSUE TITLE
Add suggested practice documentation for timestamps should use ISO8601 format

### ISSUE THREAD

**Issue by jonathanbaker** [STIXProject/stixproject.github.io#178]
In the suggested practices we should document timestamp format preferences

Bret Jordan suggested:

"Timestamp MUST follow the ISO8601 format and SHOULD include a time zone. The format MUST be in the version of ISO8601: yyyy-mm-ddThh:mm:ss+-hh:mm"

**Comment by jonathanbaker** [comment]
Documentation should be added here:

http://stixproject.github.io/documentation/suggested-practices/#creating-timestamps

**Comment by gtback** [comment]
:+1: I'm happy with @jordan2175's wording. If there is agreement, I can make the change to the text.

cc: @johnwunder @sbarnum

**Comment by johnwunder** [comment]
I'm good with the wording of what @jordan2175 suggested so long as we still have the language STRONGLY recommending the timezone offset that's already there (though feel free to modify it to make it read better).

**Comment by jordan2175** [comment]
I would even be happy with changing the SHOULD to a MUST for the timezone.  And say if you do not know the timezone, then put -0000 instead of GMT which would be +0000.

**Comment by johnwunder** [comment]
I don't think we can change a SHOULD to a MUST in the middle of a release (or even in a minor release since it would break backwards compatibility) but it's something to think about for 2.0.

BTW -0000 is defined by RFC3339. To be honest I don't completely follow how they want you to use it but I don't think it's the same as what you're describing.

**Comment by jordan2175** [comment]
Good catch.  Well lets leave it at SHOULD for now and then look at changing to a MUST for 2.0.  Add that to the list of 2.0 items to address..   We will need to figure out what the best practice will be for those unique times when you actually do not know a timezone.  My guess is you would just code it up with your timezone.  Or we overload and use something like -0000 to describe, even if it is defined elsewhere.  Not sure.. Some thing to think about and get feedback on.   A huge step forward will be just getting a defined form in the docs.

**Comment by jordan2175** [comment]
Thanks for adding this to the documentations.  I believe things like this get us so much closer to unified and constant representation of threat data.
