### ISSUE TITLE
Update suggested practices

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/stixproject.github.io#232]
The suggested practices for some constructs need to be updated based on STIX 1.2 changes. In particular:

- [x] New suggested practices for Report
- [x] Updated suggested practices for STIX_Package
- [x] Suggested practices for descriptions, now that multiple are allowed?
- [x] Review other suggested practices

**Comment by bschmoker** [comment]
assign to @sbarnum ?

**Comment by johnwunder** [comment]
I was planning on just leaving them unassigned and having people grab them as they feel able. I'm going to push a 1.2 branch as well that we can all merge against (to avoid it going live prior to 1.2 coming out).

**Comment by johnwunder** [comment]
Closed by 572ff90.

**Comment by bschmoker** [comment]
see also a27812b3b309ed89622895d7333c6a3752dbdcbe
