### ISSUE TITLE
Review hardcoded links to specific versions

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/stixproject.github.io#233]
We need to review content for links directly to 1.1.1 materials and ensure they get updated to 1.2. I don't know that these actually exist but I also wouldn't be surprised.

**Comment by gtback** [comment]
Yes, that is the correct approach. To be fair to @johnwunder, though, the `current_version` field is his doing :wink:.

**Comment by johnwunder** [comment]
Yeah I know that should cover most of it but I think there's a few places where hardcoded versions snuck in for whatever reason.

**Comment by johnwunder** [comment]
Closed by 523dbbe
