### ISSUE TITLE
All idioms need to be updated

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/stixproject.github.io#238]
For each idiom:

1. Review for whether it uses deprecated fields, if so update to not do that
2. Update the version number of the `STIX_Package` construct

**Comment by bschmoker** [comment]
This should be covered by CI, but we may need to configure it to explicitely use the 1.2 schema and then fix any run errors

**Comment by gtback** [comment]
Since everything from 1.1.1 is still valid in 1.2, CI won't catch any deprecated or non-idiomatic content. stix-validator would need to be updated to use 1.2, and also return non-zero on best practice violations, in order for CI to find this.

**Comment by bschmoker** [comment]
hmm, the way that I understand https://github.com/STIXProject/stixproject.github.io/issues/238#issue-71965565 - point 1 was that it was check for *explicitely deprecated/broken* stuff, 

@gtback you're implying that it should be broader for 'best practices' too?

**Comment by gtback** [comment]
Oh!!! I think I misinterpreted your "this should be covered by CI" comment, @bschmoker. I thought you were saying "CI will tell us all the things we need to change", such that manual inspection would not be needed. Sorry! :frowning:

**Comment by johnwunder** [comment]
Well I don't think the validator as-is will catch deprecated content, which is exactly what we need to do? If there was a flag in the validator to JUST check for deprecations and not other best practices stuff that would help here. Not sure if it's worth coding that in just for this though.

**Comment by bworrell** [comment]
@johnwunder, you are correct--the stix-validator best practices haven't been updated to catch the 1.2 deprecations. I can try to get that working this afternoon. As for the `--only-deprecated` flag, I think if we're going that route it might be worth filtering on categories or ids of best practices (which would mean we need canonical references/identifiers for STIX best practices) so you could include/exclude specific best practice checks or categories of best practices. That being said...that's a lot of work, heh.

@bschmoker, I have a [2.2.0-dev](https://github.com/STIXProject/stix-validator/tree/2.2.0-dev) branch for the stix-validator that is loaded with the most recent STIX 1.2 schemas which can be used for schema validation of the idiom samples.

**Comment by bschmoker** [comment]
Cool, thanks! 

sidenote: I should probably use that branch for https://github.com/STIXProject/stixproject.github.io/pull/246

**Comment by bworrell** [comment]
@bschmoker @johnwunder,  I just pushed some commits to the [2.2.0-dev](https://github.com/STIXProject/stix-validator/tree/2.2.0-dev) that enable the deprecation best practice checks for `@idref` use in top-level collections as well as `Related_Packages` use.

**Comment by johnwunder** [comment]
Does it check for using the deprecated fields on `STIX_Header`?

**Comment by bworrell** [comment]
@johnwunder, not yet! That actually reminds me..I should probably update python-stix to include those fields in the deprecation checks.

**Comment by bworrell** [comment]
@johnwunder, I just pushed some updates to my [2.2.0-dev](https://github.com/STIXProject/stix-validator/tree/2.2.0-dev) branch that check for more of the STIX 1.2 deprecations:

* STIX Header fields: `Title`, `Description`, `Short_Description`, `Package_Intent`
* STIX Package fields: `@idref` and `@timestamp`

I also updated some previous checks to look for fields on `Report` (like `Title` in the `Report/Header`) and ignore previously suggested but now deprecated fields/practices (when validating a 1.2 document anyway, previous documents versions should be validated against their respective rulesets).

I need to do some more testing since I made some heavy changes in the ways that applicable STIX versions for a rule are defined and evaluated, but the best practice stuff seems to be working for the most part.

**Comment by bschmoker** [comment]
thanks @bworrell - will fork and run on my own travis build and manually check for deprecations as well
