### ISSUE TITLE
Packaging idiom needs a massive re-write

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/stixproject.github.io#240]
Most of it is not applicable, after review we might determine that it should just be deprecated? Or roll the "Report" idiom into this.

**Comment by bschmoker** [comment]
:+1:  to merging with https://github.com/STIXProject/stixproject.github.io/issues/239

**Comment by bschmoker** [comment]
also, could we copy/paste that text into https://github.com/STIXProject/stixproject.github.io/issues/234?

**Comment by johnwunder** [comment]
closed by 51059c6
