### ISSUE TITLE
Profile templates and documentation need to be updated to cover report object

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/stixproject.github.io#241]
This is probably in the templates for the most part.

**Comment by bschmoker** [comment]
Is this the excel files?

**Comment by johnwunder** [comment]
Yes. I'm hoping an update to `stix_schema_spy` and a regen of the templates will fix this but we'll see.

**Comment by bschmoker** [comment]
Should be, since it's just adding the new data members

**Comment by johnwunder** [comment]
I ran through the docs and nothing needs to be updated so I'm going to close this. The samples and templates will be updated as part of the release build.
