### ISSUE TITLE
Add STIX 1.2 data model, make it the default

### ISSUE THREAD

**Issue by gtback** [STIXProject/stixproject.github.io#244]
I'm sorry if this is covered under some of the other "1.2 Final" issues, but I couldn't find it. We'll need to re-run the `rake` task (probably after updating stix-schema-spy), fix any broken links to Python documentation, etc.

**Comment by bschmoker** [comment]
:+1: you're right, it's a one-time `rake && git commit`

**Comment by johnwunder** [comment]
Well we need to update stix_schema_spy to include the new schemas, I'm working on that now.

**Comment by johnwunder** [comment]
I just did this, @gtback can you look at what needs to be updated to link to Python stuff? Probably need to add links for the Report object, etc.

**Comment by gtback** [comment]
Yeah, I'll need to work with @bworrell to make sure the documentation gets hosted at a particular URL, and that both the new 1.2 links and old 1.1.1 links continue to work (if that's indeed what we want).

**Comment by bworrell** [comment]
@gtback, I pushed python-stix docs for `stix.report.Report` in https://github.com/STIXProject/python-stix/commit/169801887f9edf5f4a0828194bfcf74ccf1a185d

**Comment by gtback** [comment]
We still need to add in links for the Report object and new/modified vocabularies. This will be easiest once python-stix 1.2.0.0 is released and the docs are built on ReadTheDocs (to verify that the links go to the correct places)
