### ISSUE TITLE
Homepage has some display issues on Safari

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/stixproject.github.io#262]
It lets you scroll to the right beyond the header and page content. Not sure why.

**Comment by bschmoker** [comment]
Weird, repro'd with a useragent switcher on Chrome.

Likely due to the `width` on [bootstrap css](https://github.com/STIXProject/stixproject.github.io/blob/master/css/bootstrap.min.css)

File as #wontfix ? Or update the CSS ?

**Comment by johnwunder** [comment]
Looks broken on chrome as well. Bootstrap is almost definitely not the problem, they do a ton of testing. It must be something we're doing.

I think we should fix it, wouldn't make it a high priority though. I can take a look at some point.

**Comment by johnwunder** [comment]
It's due to the use of `container` under `footer`

**Comment by bschmoker** [comment]
like [this one](https://github.com/STIXProject/stixproject.github.io/blob/master/css/main.css#L15)?
