### ISSUE TITLE
Data model Overview links are broken

### ISSUE THREAD

**Issue by gtback** [STIXProject/stixproject.github.io#281]
I'm just seeing the raw Markdown link syntax on the page rather than actual hyperlinks.

![img](https://cloud.githubusercontent.com/assets/1045796/9793639/0fb5dfde-57ac-11e5-99fd-b7b0fbf88451.PNG)

http://stixproject.github.io/data-model/

**Comment by sbarnum** [comment]
me too.

We should also add in the Package and Report icons.

**Comment by johnwunder** [comment]
It seems to be showing differently locally and on github.io...I noticed this a little while ago and 0607ba was supposed to fix it, but didn't. I guess I'll just convert them all to HTML links since it seems insistent on not parsing markdown.

**Comment by bschmoker** [comment]
@johnwunder you'll want to merge  https://github.com/STIXProject/stixproject.github.io/commit/dbf3468066005a245587d07672d98b6beefd0c94

**Comment by johnwunder** [comment]
I tried that too, it didn't actually work either. It renders differently when you run it locally in Jekyll and when github.io hosts it (probably why we both thought we fixed it when we didn't).

I did fix it in 9af3a185, so closing this.
