### ISSUE TITLE
Update STIX 2.0 landing page to point to the CybOX cover page

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/stixproject.github.io#322]
The STIX 2.0 landing page (/stix2.0) needs to be updated to have the CybOX link for the pre-draft specification point to the cover page: https://docs.google.com/document/d/1eIl5iBR7vQd_8kgxFWt3bCaxG8WjtqutdjuW9n1iXaI/edit

**Comment by clenk** [comment]
Closed in 57e38dc.
