### ISSUE TITLE
Broken links on TOC that contain question marks

### ISSUE THREAD

**Issue by gtback** [STIXProject/stixproject.github.io#332]
See [this page](http://stixproject.github.io/about/). It may affect other pages as well.

For instance: 

http://stixproject.github.io/about/#who-is-stix-for?-what-does-stix-do-for-me?
vs 
http://stixproject.github.io/about/#who-is-stix-for-what-does-stix-do-for-me

This is low priority.

**Comment by clenk** [comment]
Fixed in 762a54af.

**Comment by gtback** [comment]
Looks great, thanks @clenk !
