### ISSUE TITLE
Invalid link to PDF download

### ISSUE THREAD

**Issue by coverband** [STIXProject/stixproject.github.io#333]
On [Getting Started > Whitepaper](http://stixproject.github.io/getting-started/whitepaper/)
the link to download a PDF version of the whitepaper returns a 404.

http://stix.mitre.org/about/documents/STIX_Whitepaper_v1.1.pdf

Additionally,  issue #234 suggests the WP version is behind and needs to be updated.

**Comment by gtback** [comment]
Thanks, @coverband. Yes, the whitepaper is for an older version of STIX. A lot of it still applies to 1.2, but some things have changed. A lot *more* has changed for STIX 2.0, now in development.
